main.py
from flask import Flask
from routes.home import home_route
from routes.clientes import cliente_route

#Inicialização
app = Flask(__name__)

app.register_blueprint(home_route)
app.register_blueprint(cliente_route, url_prefix='/clientes')

# Indicar que estamos no modo desenvolvedor para n encerar a aplicação a cada alteração
app.run(debug=True)

routes/clientes.py
from flask import Blueprint, render_template, request
from database.cliente import CLIENTE

"""
Rota clientes 

 - /clientes/ (GET): Listar todos os clientes
 - /clientes/ (POST): Cadastrar um novo cliente
 - /clientes/new (GET): Formulário para cadastrar um novo cliente
 - /clientes/id (GET): Exibir um cliente específico
 - /clientes/id/edit (GET): Formulário para editar um cliente
 - /clientes/id/updade (PUT): Atualizar um cliente
 - /clientes/id/delete (DELETE): Deletar um cliente

"""

cliente_route = Blueprint('cliente', __name__)

@cliente_route.route('/')
def lista_clientes():
    return render_template('lista_clientes.html', clientes=CLIENTE)

@cliente_route.route('/', methods=['POST'])
def inserir_cliente():
    data = request.json

    novo_usuario = {
        'id': len(CLIENTE) + 1,
        'nome': data['nome'],
        'email': data['email'],
    }

    CLIENTE.append(novo_usuario)
    return render_template('item_cliente.html', cliente=novo_usuario)

@cliente_route.route('/new')
def form_cliente():
    return render_template('form_cliente.html') 

@cliente_route.route('/<int:cliente_id>')
def detalhe_cliente(cliente_id):
    return render_template('detalhe_cliente.html') 

@cliente_route.route('/<int:cliente_id>/edit')
def form_edit_cliente(cliente_id):
    return render_template('form_edit_cliente.html')

@cliente_route.route('/<int:cliente_id>/update', methods=['PUT'])
def update_cliente(cliente_id):
    pass

@cliente_route.route('/<int:cliente_id>/delete', methods=['DELETE'])
def delete_cliente(cliente_id):
    pass

routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')
def home():
    return render_template('index.html')

templates/form_cliente.html
<form class="c-form" 
action="{{ url_for('cliente.inserir_cliente') }}" 
method="post"
c-append="#lista_clientes">

    <div class="mb-3">
      <label class="form-label">Nome</label>
      <input type="text" class="form-control" name="nome">
    </div>

    <div class="mb-3">
      <label id="label-target" class="form-label">Email</label>
      <input type="text" class="form-control" name="email">
    </div>

    <button type="submit" class="btn btn-primary">Adicionar Cliente </button>
  </form>

templates/index.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">

  <title>Hello, world!</title>
</head>

<body>
  <div class="container">
    <h1 class="text-center">Gestão de cliente</h1>
    <!-- Add cliente -->
    <div c-container="{{ url_for('cliente.form_cliente')}}"></div>

    <hr>
    <!-- Lista de clientes -->
    <h2>Lista de clientes</h2>
    <div c-container="{{ url_for('cliente.lista_clientes') }}"></div>
  </div>


  <script src="{{ url_for('static', filename='js/cru.js')}}" />
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>
</body>

</html>

templates/item_cliente.html
<tr>
    <th scope="row">{{ cliente.id }}</th>
    <td>{{ cliente.nome }}</td>
    <td>{{ cliente.email }}</td>
    <td>
        <button type="button" class="btn btn-primary">Editar</button>
        <button type="button" class="btn btn-danger">Excluir</button>
    </td>
</tr>

templates/lista_clientes.html
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Email</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody id="lista_clientes">

{% for cliente in clientes %}

      {% include 'item_cliente.html' %}

{% endfor %}
      
    </tbody>
  </table>